CREATE TABLE EDC_Export (
	Area INTEGER DEFAULT NULL,
	SocCode CHAR(7) DEFAULT NULL,
	GeoLvl SMALLINT DEFAULT NULL,
	Level1 DECIMAL(8,2) DEFAULT NULL,
	Level2 DECIMAL(8,2) DEFAULT NULL,
	Level3 DECIMAL(8,2) DEFAULT NULL,
	Level4 DECIMAL(8,2) DEFAULT NULL,
	Average DECIMAL(8,2) DEFAULT NULL
);