CREATE TABLE Onet_Occs (
	OnetCode CHAR(10) DEFAULT NULL,
	OnetTitle VARCHAR(105) DEFAULT NULL,
	OnetDescription TEXT DEFAULT NULL,
	JobZone SMALLINT DEFAULT NULL,
	DOLTraining SMALLINT DEFAULT NULL
);