CREATE TABLE xwalk_plus (
	OES_SOCCODE CHAR(7) DEFAULT NULL,
	OES_SOCTITLE VARCHAR(105) DEFAULT NULL,
	TruncOnetCode CHAR(7) DEFAULT NULL,
	OnetCode CHAR(10) DEFAULT NULL,
	ONetTitle VARCHAR(105) DEFAULT NULL
);